image: "python:3.6"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source $CI_PROJECT_DIR/venv/bin/activate

build:
  stage: build
  script:
    - pip install -e .[dev]

typecheck:
  stage: test
  script:
    - $CI_PROJECT_DIR/venv/bin/mypy .

test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/venv/bin
    - ls -lisah
    - $CI_PROJECT_DIR
    - $CI_PROJECT_DIR/venv/bin/pytest .

trigger_build:
  stage: deploy
  only:
    - master
  script:
    - "curl -X POST -F token=159283888a03644a78e683b72d8c55 -F ref=master https://gitlab.hpi.de/api/v4/projects/3536/trigger/pipeline"
